---
- name: Give core team admin access
  authorized_key: user="{{admin_user}}" state="present" key="https://github.com/{{item}}.keys"
  with_items:
      - adriaanm
      - lrytz
      - SethTisue
      - retronym
      - szeiger

- name: Install basic packages
  apt: name={{item}} state=present
  with_items:
       - acl # so that become_user works (uses setfacl)
       - apt-transport-https
       - openjdk-8-jdk
       - git

- name: Install sbt-extras
  get_url:
      url: "{{sbt_extras_url}}"
      dest: "{{sbt_extras_path}}"
      owner: root
      mode: "755"
